### ISSUE TITLE
TI software version

### ISSUE THREAD

**Issue by Mathew444** [nspiredev500/OSExt#7]
Hey, first of all i really like your project and cant wait to try the mini clock it seems to that this is the only working one right now but i cant get it to work on my TI-Nspire cx cas when i start the file my TI just reboots. I have version 4.5.0.1180 installed on my TI and i am using Ndless 4.5.0. 
Clould you tell me what version you were using in your testing and how i should install it correctly.

**Comment by Mathew444** [comment]
After further trying i found out that the first version of OSExt works just fine on my nspire.
Maybe that helps to find the bug. I really love your work!

**Comment by nspiredev500** [comment]
Can you tell me the exact revision of Ndless you have or try the newest one?
I don't know if i accidentally use an Ndless syscall that is only in the newest version, so that could cause a crash.
Also, do you have a CAS or non-CAS?
There are hooks in my programm that are specific to the os and I only have a CAS one to test it, I can only test non-CAS in firebird.

**Comment by nspiredev500** [comment]
Here is the latest build with only the clock enabled. If it works, I know it's in the other modules.
I also added a check for the latest ndless revision. If you see a message when trying to start it it means you don't have the latest ndless revision. Also I tried it today on another CX CAS and it worked fine, so it's not just my calculator.
The only other thing could be your hardware revision. The letters on the back of you nspire are the hardware revision. Some of my code might only work for hardware W+, but I looked at it and it shouldn't crash because of that, it only wouldn't display anything.
EDIT: I tested it in firebird for hw j to w and it didn't crash, it just didn't display anything like I thought. I guess that's not the problem

[OSExt.zip](https://github.com/nspiredev500/OSExt/files/3811059/OSExt.zip)

**Comment by nspiredev500** [comment]
Also here is my Ndless for you to try. Don't worry because it doesn't display the green "Ndless installed!" message, I removed that for myself because I find it distracting (and thinking about it, it might draw over the clock, I remember it to be in that area, but that would only be a cosmetic issue).

[Ndless.zip](https://github.com/nspiredev500/OSExt/files/3811159/Ndless.zip)

**Comment by Mathew444** [comment]
I have a CAS. Where do i have to look exactly to find out my hardware revision? The second part is P-NNNNX (N are numbers). I tried your Ndless version because using mine it showed up the message but on yours it did too and the green text showed up too so im not really sure if you put the wrong file or if I installed it wrong. This is the version i was using before and i am pretty sure it is the newest one
[My_Ndless.zip](https://github.com/nspiredev500/OSExt/files/3811298/My_Ndless.zip)

**Comment by Mathew444** [comment]
I tried your newest release and the clock works. Whatever caused the problem in your second release is fixed now. When i tried to open the settings menu with ctrl + s as described in release 2 nothing happend.

**Comment by nspiredev500** [comment]
Have you used the one I provided you here or from the actual release?
If it's from here, I disabled everything but the clock. If it's from the release, my instructions weren't clear. I'm working on proper documentation now. To get to the settings, you first have to use ctrl + comma to get to the "desktop" and then ctrl + s to get to the settings.
You should upgrade your ndless anyways, some programm (or OSExt in the future) could need the latest version of ndless.
To upgrade your ndless release, you have to delete your ndless_ressources and your ndless_installer (maybe not the installer, but to be sure delete it anyways) and then put the new files from the release there. If you haven't already, reboot your calculator. Then run the new ndless_installer.

[Ndless releases](https://github.com/ndless-nspire/Ndless/releases)

**Comment by Mathew444** [comment]
Upgraded ndless succesfully now i only replaced the installer last time that was my mistake. Also when in the settings menu i am unable to switch between the options because b and p scroll the whole menu and not just the green selected part. Maybe it would be easier if you could use the d pad to select things and right and left the change the value.

**Comment by nspiredev500** [comment]
You have to use shift + b and shift + p. I'm looking into how to use the clickpad. But for things like a password you can't just change a number, so it has to be more than left or right.

**Comment by nspiredev500** [comment]
Changed it to up and down for selection and shift + up/down for scrolling in the development branch.
Maybe I make a new release tomorrow.

**Comment by Mathew444** [comment]
Sounds good!

**Comment by nspiredev500** [comment]
Sorry, no touchpad controll for now, on my calc it seems it's skipping the sleep when I let it use the touchpad, so all input is registered hyper-fast and you cant type anything
